export const ACCOUNT_DETAILS_CONSTANT = {
    FETCH_ACCOUNT_DETAILS_STARTED: "FETCH_ACCOUNT_DETAILS_STARTED",
    FETCH_ACCOUNT_DETAILS_SUCCESS: "FETCH_ACCOUNT_DETAILS_SUCCESS",
    FETCH_ACCOUNT_DETAILS_ERROR: "FETCH_ACCOUNT_DETAILS_ERROR",
};
